// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Chat documents */
interface ChatDocumentData {
  /**
   * Nom field in *Chat*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: chat.nom
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  nom: prismic.KeyTextField;
  /**
   * Image field in *Chat*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: chat.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
  /**
   * Sexe field in *Chat*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Mâle
   * - **API ID Path**: chat.sexe
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  sexe: prismic.SelectField<"Mâle" | "Femelle", "filled">;
  /**
   * Date de naissance field in *Chat*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: chat.date_de_naissance
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/date
   *
   */
  date_de_naissance: prismic.DateField;
  /**
   * Identifié par puce électronique field in *Chat*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: chat.identifie_par_puce_electronique
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  identifie_par_puce_electronique: prismic.BooleanField;
  /**
   * Vaccinée field in *Chat*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: chat.vaccinee
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  vaccinee: prismic.BooleanField;
  /**
   * Déparasitée field in *Chat*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: chat.deparasitee
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  deparasitee: prismic.BooleanField;
  /**
   * Testé SIDA field in *Chat*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Pas testé
   * - **API ID Path**: chat.teste_sida
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  teste_sida: prismic.SelectField<
    "Pas testé" | "Positif" | "Négatif",
    "filled"
  >;
  /**
   * Testé Leucose field in *Chat*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Pas Testé
   * - **API ID Path**: chat.teste_leucose
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  teste_leucose: prismic.SelectField<
    "Pas Testé" | "Positif" | "Négatif",
    "filled"
  >;
  /**
   * Certificat de bonne santé field in *Chat*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: chat.certificat_de_bonne_sante
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  certificat_de_bonne_sante: prismic.BooleanField;
  /**
   * Carnet de santé field in *Chat*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: chat.carnet_de_sante
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  carnet_de_sante: prismic.BooleanField;
  /**
   * Prescription future stérilisation field in *Chat*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: chat.prescription_future_sterilisation
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  prescription_future_sterilisation: prismic.BooleanField;
  /**
   * Habitue avec chien field in *Chat*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: chat.habitue_avec_chien
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  habitue_avec_chien: prismic.BooleanField;
  /**
   * Habitue avec chats field in *Chat*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: chat.habitue_avec_chats
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  habitue_avec_chats: prismic.BooleanField;
  /**
   * Caractère field in *Chat*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: chat.caractere
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  caractere: prismic.RichTextField;
  /**
   * Ville famille d’accueil field in *Chat*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: chat.ville_famille_daccueil
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  ville_famille_daccueil: prismic.KeyTextField;
  /**
   * Réservé field in *Chat*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: chat.reserve
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  reserve: prismic.BooleanField;
  /**
   * Adopté field in *Chat*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: chat.adopte
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  adopte: prismic.BooleanField;
  /**
   * Slice Zone field in *Chat*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: chat.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<ChatDocumentDataSlicesSlice>;
  /**
   * Meta Title field in *Chat*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: chat.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
  /**
   * Meta Description field in *Chat*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: chat.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismic.KeyTextField;
  /**
   * Meta Image field in *Chat*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: chat.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
}
/**
 * Slice for *Chat → Slice Zone*
 *
 */
type ChatDocumentDataSlicesSlice = MediaItemSlice;
/**
 * Chat document from Prismic
 *
 * - **API ID**: `chat`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ChatDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ChatDocumentData>, "chat", Lang>;
export type AllDocumentTypes = ChatDocument;
/**
 * Item in MediaItem → Items
 *
 */
export interface MediaItemSliceDefaultItem {
  /**
   * Media field in *MediaItem → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: media_item.items[].media
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  media: prismic.LinkToMediaField;
}
/**
 * Default variation for MediaItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MediaItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<MediaItemSliceDefaultItem>
>;
/**
 * Slice variation for *MediaItem*
 *
 */
type MediaItemSliceVariation = MediaItemSliceDefault;
/**
 * MediaItem Shared Slice
 *
 * - **API ID**: `media_item`
 * - **Description**: `MediaItem`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MediaItemSlice = prismic.SharedSlice<
  "media_item",
  MediaItemSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      ChatDocumentData,
      ChatDocumentDataSlicesSlice,
      ChatDocument,
      AllDocumentTypes,
      MediaItemSliceDefaultItem,
      MediaItemSliceDefault,
      MediaItemSliceVariation,
      MediaItemSlice,
    };
  }
}
